### ISSUE TITLE
List Firefox features to be disabled

### ISSUE THREAD

**Issue by chrmod** [ghostery/user-agent-desktop#18]
(**Disclaimer**: For each feature I—Rémi—put some places where changes need to happen; in case there are multiple things in the same file, I just put one link so let's be sure to scan each file for changes).

Examples:
* sync:
  * *Firefox accounts*: https://github.com/human-web/user-agent-desktop/pull/6/files#diff-9e862dcfcd232dc88f025d255b4e1144R458
  * https://github.com/human-web/user-agent-desktop/pull/6/files#diff-9b4f4d85c2d17ac3e376190ef7cc0378R15
  * https://github.com/human-web/user-agent-desktop/pull/6/files#diff-245f392704a166ee94ee8dcc7f57dca0R163
  * https://github.com/human-web/user-agent-desktop/pull/6/files#diff-5afd12f5be86533b8dbc7f45e5b27498R1149
  * https://github.com/human-web/user-agent-desktop/pull/6/files#diff-48e427972d881aa8169e03ff6473987aR765
  * https://github.com/human-web/user-agent-desktop/pull/6/files#diff-d5090a36a4139d9c7f866acd30c50da4R37
  * https://github.com/human-web/user-agent-desktop/pull/6/files#diff-cef53509552274ae809ff183f3394680R94
  * https://github.com/human-web/user-agent-desktop/pull/6/files#diff-876f110dd0ec8f5ef95185f657977e9eR394
  * https://github.com/human-web/user-agent-desktop/pull/6/files#diff-876f110dd0ec8f5ef95185f657977e9eR1135
  * https://github.com/human-web/user-agent-desktop/pull/6/files#diff-78edc04f5fd7f14f6c33615a003f60f8R322
  * For more grep for `#ifdef MOZ_SERVICES_SYNC`.
* pocket:
  * https://github.com/human-web/user-agent-desktop/pull/6/files#diff-40aea7a8c44ea3184dca42778fcdc35cR79
  * https://github.com/human-web/user-agent-desktop/pull/6/files#diff-876f110dd0ec8f5ef95185f657977e9eR555
  * https://github.com/human-web/user-agent-desktop/pull/6/files#diff-876f110dd0ec8f5ef95185f657977e9eR1059
* tracking protection (protection dashboard + shield)
  * https://github.com/human-web/user-agent-desktop/pull/6/files#diff-876f110dd0ec8f5ef95185f657977e9eR882
  * https://github.com/human-web/user-agent-desktop/pull/6/files#diff-c1256651c0fbbf45fbf7fd55eb379380R925
  * https://github.com/human-web/user-agent-desktop/pull/6/files#diff-876f110dd0ec8f5ef95185f657977e9eR882
* activity stream
  * https://github.com/human-web/user-agent-desktop/pull/6/files#diff-48e427972d881aa8169e03ff6473987aR15
  * https://github.com/human-web/user-agent-desktop/pull/6/files#diff-cef53509552274ae809ff183f3394680R29
* logins & passwords
* Firefox studies

Each such featue should get a dedicated issue with appropriate label as it is likely we will be getting back to those issues in the furute as Firefox code will be changing.

**Comment by sammacbeth** [comment]
Current status:

 - [x] Sync - Disabled via pref: https://github.com/ghostery/user-agent-desktop/blob/fa94d2f289f6497fe405f6f6f57f4f1a559f986a/branding/ghostery/pref/firefox-branding.js#L101
 - [x] Pocket - Disabled via pref: https://github.com/ghostery/user-agent-desktop/blob/fa94d2f289f6497fe405f6f6f57f4f1a559f986a/branding/ghostery/pref/firefox-branding.js#L100
 - [x] Tracking protection UI - disabled in #125. 
 - [ ] Tracking protection blocking - can done via pref
 - [ ] Activity stream - Soft disabled via new tab page change #115. Preferences page still exists #60 #179 
 - [ ] Login & Passwords - This feature is heavily branded with Firefox's Lockwise brand. We could either remove the feature, or remove the Firefox branding from it. Features such as password breach alerts can be disabled.
 - [ ] Firefox studies - remove the setting in 'Ghostery Data Collection and Use' section of preferences.
 - [ ] Default bookmarks - Change bookmarks in a new profile, switch Mozilla links for ghostery ones.
 - [ ] Recommended addons - Displayed on `about:addons`. See #196
 - [ ] What's New - In burger menu

**Comment by chrmod** [comment]
@sammacbeth I would say we can close this issues individual topics are already covered by own issues. What do you think?
